name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write


jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AyeshaNasirWebDeveloper
          outputs: |
            dist/github-snake.svg?color_snake=#14532D&color_dots=#E8F5E9,#BBF7D0,#86EFAC,#22C55E,#14532D
            dist/github-snake-dark.svg?color_snake=#22C55E&color_dots=#052E16,#14532D,#166534,#16A34A,#22C55E
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
          commit_message: "Update green snake animation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
